#!/usr/bin/env python3
# Copyright (C) [2026] [michael@aloecraft.org]
# Licensed under the Apache License, Version 2.0.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
"""Regenerate the vendored schema.org snapshot from a pinned release.

The snapshot this replaced was an unreproducible capture of `version/latest`
taken partway through schema.org's 30.0 development window: it matched no
published release, and carried two synthetic root nodes (`rdfs:Class` and
`rdf:Property`) that appear in no release at all. Nothing recorded which
ontology it was, so no consumer could tell.

This script is the fix. The release is pinned, the source is a URL that
serves every release permanently, and the generated module records both the
release and a fingerprint of its graph -- so the file can be regenerated and
verified rather than trusted.

    python3 script/vendor_schemaorg.py            # regenerate at RELEASE
    python3 script/vendor_schemaorg.py --release 30.0

`schema.org/version/<n>/` only serves whichever release is current, so it
cannot be pinned; the schemaorg repository keeps every release. The two
differ in their `@context` prefix aliases for the same release, which is why
the fingerprint covers `@graph` -- the terms -- and not the context block.
"""

import argparse
import json
import subprocess
import sys
import urllib.request
from pathlib import Path

try:
    from aloeschema.data import graph_fingerprint
except ImportError:  # pragma: no cover
    sys.exit("aloeschema is not importable -- run `pip install -e .` first")

RELEASE = "30.0"
SOURCE = (
    "https://raw.githubusercontent.com/schemaorg/schemaorg/main"
    "/data/releases/{release}/schemaorg-current-https.jsonld"
)

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data"
TARGET = DATA / "schemaorg_current.py"
RELEASE_MODULE = DATA / "release.py"
HEADER = TARGET.read_text().split("\n\n")[0] if TARGET.exists() else ""


def fetch(release):
    url = SOURCE.format(release=release)
    with urllib.request.urlopen(url, timeout=120) as r:
        return url, json.loads(r.read().decode("utf-8"))


GENERATED = (
    "# GENERATED by script/vendor_schemaorg.py -- do not edit by hand.\n"
    "# Regenerate with: python3 script/vendor_schemaorg.py\n"
)


def render_release(release, url, data):
    """The recorded facts, in a module cheap enough to import on its own.

    Kept apart from the snapshot so that reading the release costs a small
    import rather than parsing 1.5 MB of ontology. The two can therefore
    disagree, which is what script/checks.py exists to catch.
    """
    return (
        f"{HEADER}\n\n"
        f"{GENERATED}"
        f'"""Which schema.org release the vendored snapshot holds.\n\n'
        f"SCHEMAORG_GRAPH_SHA256 fingerprints the snapshot's `@graph` -- the\n"
        f"terms -- and not its `@context`, whose prefix aliases differ between\n"
        f'schema.org and the schemaorg repository for one and the same release.\n"""\n\n'
        f'SCHEMAORG_RELEASE = "{release}"\n'
        f'SCHEMAORG_GRAPH_SHA256 = "{graph_fingerprint(data)}"\n'
        f'SCHEMAORG_SOURCE = "{url}"\n'
    )


def render_snapshot(data):
    body = json.dumps(data, indent=4, ensure_ascii=False)
    return (
        f"{HEADER}\n\n"
        f"{GENERATED}"
        f"#\n"
        f"# The release this holds is recorded in release.py beside it, and\n"
        f"# script/checks.py verifies the two agree.\n\n"
        f"schemaorg_current_jsonld = {body}\n"
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--release", default=RELEASE)
    args = ap.parse_args()

    url, data = fetch(args.release)
    nodes = len(data["@graph"])
    print(f"fetched  {url}\n         {nodes} graph nodes")

    TARGET.write_text(render_snapshot(data))
    RELEASE_MODULE.write_text(render_release(args.release, url, data))
    for f in (TARGET, RELEASE_MODULE):
        print(f"wrote    {f.relative_to(ROOT)}")

    if subprocess.run(
        ["ruff", "format", "-q", str(TARGET), str(RELEASE_MODULE)]
    ).returncode:
        print("ruff format failed", file=sys.stderr)
        return 1
    print(f"release  {args.release}\nsha256   {graph_fingerprint(data)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
