# Copyright (C) [2026] [michael@aloecraft.org]
# Licensed under the Apache License, Version 2.0.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License

# GENERATED by script/vendor_schemaorg.py -- do not edit by hand.
# Regenerate with: python3 script/vendor_schemaorg.py
"""Which schema.org release the vendored snapshot holds.

SCHEMAORG_GRAPH_SHA256 fingerprints the snapshot's `@graph` -- the
terms -- and not its `@context`, whose prefix aliases differ between
schema.org and the schemaorg repository for one and the same release.
"""

SCHEMAORG_RELEASE = "30.0"
SCHEMAORG_GRAPH_SHA256 = (
    "21331b9baa07d76266d8225d01e8a65ff50c43674b2b4fea4011e2af9009087c"
)
SCHEMAORG_SOURCE = "https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/30.0/schemaorg-current-https.jsonld"
